#!/usr/bin/env python

__author__ = 'Sergei Egorichev <zoltonmd@gmail.com>'
__date__ = '23 Nov 2015'
__version__ = '0.1.0'

"""
What:    /proc/diskstats
Date:    February 2008
Contact:  Jerome Marchand <jmarchan@redhat.com>
Description:
    The /proc/diskstats file displays the I/O statistics
    of block devices. Each line contains the following 14
    fields:
     1 - major number
     2 - minor mumber
     3 - device name
     4 - reads completed successfully
     5 - reads merged
     6 - sectors read
     7 - time spent reading (ms)
     8 - writes completed
     9 - writes merged
    10 - sectors written
    11 - time spent writing (ms)
    12 - I/Os currently in progress
    13 - time spent doing I/Os (ms)
    14 - weighted time spent doing I/Os (ms)
    For more details refer to Documentation/iostats.txt

My two cents:

    r_await = 'time spent reading'/'reads completed successfully'
    w_await = 'time spent writing'/'writes completed'
    await   = ('time spent reading'+'time spent writing')/('reads completed successfully'+'writes completed')
"""

import sys

class Diskstats():

    def __init__(self, name):
        diskstats = '/proc/diskstats'
        file = open(diskstats, 'rb')
        for row in file:
            stats = row.split()
            if stats[2] == name:
                self.stats = stats

        self.w_await = float(self.stats[10])/int(self.stats[7])
        self.r_await = float(self.stats[6])/int(self.stats[3])
        self.await = (float(self.stats[6])+float(self.stats[10]))/\
                     (float(self.stats[7])+float(self.stats[3]))


def main():

    help= """
    Usage: await_get [param] disk_name

        params:
           r_await - The  average  time  (in milliseconds) for read requests issued
                     to the device to be served. This includes the time spent by
                     the requests in queue and the time spent servicing them.
           w_await - The average time (in milliseconds) for write requests issued
                     to the device to be served. This includes the time  spent  by
                     the requests in queue and the time spent servicing them.
           await   - The average time (in milliseconds) for I/O requests issued
                     to the device to be served. This includes the time spent by
                     the requests in queue and the time spent servicing them.
    """
    try:
        sys.argv[1]
        sys.argv[2]
    except IndexError:
        print help
        sys.exit()

    if sys.argv[1] == 'r_await':
        disk = Diskstats(sys.argv[2])
        print disk.r_await
    elif sys.argv[1] == 'w_await':
        disk = Diskstats(sys.argv[2])
        print disk.w_await
    elif sys.argv[1] == 'await':
        disk = Diskstats(sys.argv[2])
        print disk.await
    else:
        print help

if __name__ == '__main__':
    main()
